version: '3.7'
services:
    postgres:
        image: postgres:11.2-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: password
        ports:
        - "5432:5432"
        volumes:
        - ./volumes/postgres/:/var/lib/postgresql/data/

    postgrest:
        image: postgrest/postgrest
        ports:
        - "3000:3000"
        environment:
            PGRST_DB_URI: postgres://postgres:password@postgres/postgres
            PGRST_DB_ANON_ROLE: postgres

    swagger:
        image: swaggerapi/swagger-ui
        ports:
            - "8080:8080"
        expose:
            - "8080"
        environment:
            API_URL: http://127.0.0.1:3000/
